# application config
server:
  port: ${SERVER_PORT:8111}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/payment/command/api}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:0357e529af170e9b9a2cadefae81c557584f467d180fbc31581a3542612b224c}

  # hibernate config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      naming:
        physical-strategy: ${HIBERNANTE_NAMING:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl}

  # datasource config
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/PaymentCommandService}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:12345678}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}

  # mail config
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:habolabu@gmail.com}
    password: ${MAIL_PASSWORD:accjvicqwbrkgska}
    properties.mail.smtp:
      auth: ${MAIL_SMTP_AUTH:true}
      starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
      ssl.trust: ${MAIL_SMTP_SSL_TRUST:smtp.gmail.com}
    protocol: ${MAIL_PROTOCOL:smtp}
    test-connection: ${MAIL_TEST_CONNECTION:false}

  # twilio config
  twilio:
    accountSID: ${TWILLIO_ACCOUNT_SID:AC1dc7baac41475a5ecf3eeee27c07369c}
    authToken: ${TWILLIO_AUTH_TOKEN:d22b42e1c2504aae4c5f7c438767daa2}
    sender: ${TWILLIO_SENDER:+17623025805}

  # momo config
  momo:
    partnerCode: ${MOMO_PARTNER_CODE:MOMOO41P20220925}
    accessKey: ${MOMO_ACCESS_KEY:vadZX1Lzmi9Q19p7}
    secretKey: ${MOMO_SECRET_KEY:25pcD9OHzsP1WDGOBPRYEoHoR6n30sn8}
    api: ${MOMO_API:https://test-payment.momo.vn/v2/gateway/api/create}
    notifyURL: ${MOMO_NOTIFY_URL:http://localhost:8080/payment/command/api/bill/pay/complete/%d}

  # thread pool config
  threadPool:
    corePoolSize: ${THREAD_POOL_CORE_POOL_SIZE:5}
    maxPoolSize: ${THREAD_POOL_MAX_POOL_SIZE:10}
    queueCapacity: ${THREAD_POOL_QUEUE_CAPACITY:25}